# download base image from docker hub, we are going to use 16-alpine
FROM node:16-alpine

WORKDIR '/app'

# install dependencies program
COPY ./package.json ./
RUN npm install
COPY ./ ./

# run container using following commands
CMD ["npm", "run", "start"